### PR TITLE
Update tap to the latest 5.7

### PR DESCRIPTION
**Pull request by ariya**

### CODE REVIEW

**Comment by thlorenz** [comment]
Do all tests pass with this latest tap version?

**Comment by thlorenz** [comment]
Looks like we need to upgrade to npm 2 for install to work. [failure](https://travis-ci.org/thlorenz/redeyed/jobs/112056114)
Also let's remove older nodes from the tests.

Could you please update the `.travis.yml` to:

```yaml
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
before_install:
  - npm install -g npm@2
```
and submit with this PR?

Thanks

**Comment by ariya** [comment]
Sure, it's a good hygiene anyway to update Node.js/npm versions.

**Comment by ariya** [comment]
Still failing. I may not have enough time to learn tap right now. I don't mind if someone beats me to it.

**Comment by ariya** [comment]
According to http://www.node-tap.org/changelog/, looks like there will be some more work involved when upgrading tap from 0.x to any version.

**Comment by ariya** [comment]
I found the issue: `t.end()` is now mandatory, even if there is a subtest.

**Comment by ariya** [comment]
Now the failures are legit: they are caused by some dependencies having its `.js` file as ES6 module. Right now redeyed only parse scripts and it can't detect modules properly. I'll file a separate enhancement issue for that.

**Comment by ariya** [comment]
I was wrong, the module parsing is a red herring. The problem is that there are too many `*.js` files (this is recursively searched in `node_modules` after all) which do not have any `var` declaration (the testing reference inside `redeyed-smoke`). Those files need to excluded from the test for the test to succeed. I'll see if I can hunt most of the files for the exclusion.

In the long run, we need to reconsider the value of such a smoke test. It highly depends on other modules directly and indirectly installed by the dependencies (`tap` and others). It is also a moving target cause the dependencies are not strictly locked, only via `~` version comparator.

**Comment by ariya** [comment]
@thlorenz This should be good to go now!

**Comment by ariya** [comment]
@thlorenz Would you like to review this first and shall I merge it?

**Comment by ariya** [comment]
Since there is no objection, likely I will merge this soon!

**Pull request merged**
